### ISSUE TITLE
localhost:8545/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by drandreaskrueger** [energywebfoundation/bond#10]
Subtitle of your repo   
https://github.com/energywebfoundation/ew-link-origin

says:

> The EWF-link origin app integrates green energy assets to the coo smart-contracts. http://origin.energyweb.org/

the URL then redirects to 

http://origin.energyweb.org/0x9715f1a4df2d42d71ff74d9cc07715b20843fd0a

which ... is an empty page.

Console (Ctrl-Shift-J) shows

```
Download the React DevTools for a better development experience: https://fb.me/react-devtools

localhost:8545/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED

errors.js:42 Uncaught (in promise) Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (errors.js:42)
    at XMLHttpRequest.request.onreadystatechange (index.js:73)
```

Your app should work without me running a node at localhost:8545, no?

**Comment by cerealkill** [comment]
HI Andreas,

Origin is a DAPP and therefore you need to have metamask installed running and connected to a tobalaba node. That is why it tries to connect to `localhost:8545`. This issue also doesn't concern the `ew-link-origin` app since this is a hardware project to integrate energy assets into the origin smart-contracts, to point issues in the DAPP please address [ew-origin](https://github.com/energywebfoundation/ew-origin) repository.

**Comment by drandreaskrueger** [comment]
Thanks @cerealkill 

Good to know.

But to hand out that explanation only to people who dig so deep that they actually open a github repo issue ... is suboptimal.

Solution:

Show "you need to have metamask installed" when someone like me arrives at

http://origin.energyweb.org/
